/**
 * Apothecary: a curated list of supplements, herbs, and TCM formulas.
 *
 * Every ASIN here was resolved against Amazon search and verified to point
 * to a live product page. Links use tag=spankyspinola-20.
 *
 * Affiliate disclosure: Immune Rebuilt is a participant in the Amazon Services
 * LLC Associates Program. As an Amazon Associate we earn from qualifying
 * purchases. This earns us a small commission at no extra cost to you.
 */
export type Family = "Supplement" | "Herb" | "TCM" | "Adaptogen" | "Topical";
export type Item = {
  asin: string;
  title: string;
  brand: string;
  family: Family;
  category: string;
  whyHere: string;
  bestFor: string;
  warning?: string;
  internalSlug?: string;
};

const T = "spankyspinola-20";
export const amazonUrl = (asin: string) => `https://www.amazon.com/dp/${asin}?tag=${T}`;

export const APOTHECARY: Item[] = [
  { asin: "B01N6E26ZX", title: "L-Glutamine powder, unflavored", brand: "Pure Encapsulations", family: "Supplement", category: "Gut barrier", whyHere: "The most studied amino acid for enterocyte fuel and tight-junction support.", bestFor: "Active leaky-gut symptoms", internalSlug: "leaky-gut-without-the-hype" },
  { asin: "B0CBW4VBTD", title: "Slippery elm bark powder", brand: "Starwest Botanicals", family: "Herb", category: "Gut barrier", whyHere: "A demulcent mucilage that coats irritated mucosa.", bestFor: "Reflux, IBS-style discomfort", internalSlug: "leaky-gut-without-the-hype" },
  { asin: "B008SC8ZDG", title: "DGL deglycyrrhizinated licorice chewable", brand: "Enzymatic Therapy", family: "Herb", category: "Gut barrier", whyHere: "Soothes gastric mucosa without raising blood pressure.", bestFor: "Reflux, gastritis", warning: "Avoid full-glycyrrhizin licorice if you have hypertension.", internalSlug: "leaky-gut-without-the-hype" },
  { asin: "B000302280", title: "Marshmallow root capsules", brand: "Nature's Way", family: "Herb", category: "Gut barrier", whyHere: "Demulcent, gentle, complements slippery elm.", bestFor: "Dry-mouth, dry-throat, irritated gut" },
  { asin: "B019G9OZ2O", title: "Aloe vera inner-leaf juice, decolorized", brand: "Lily of the Desert", family: "Herb", category: "Gut barrier", whyHere: "Decolorized aloe avoids the laxative anthraquinones.", bestFor: "Inflamed gut lining", warning: "Do not use whole-leaf aloe long term." },
  { asin: "B0035BYOSA", title: "Zinc carnosine 75 mg", brand: "Doctor's Best (PepZin GI)", family: "Supplement", category: "Gut barrier", whyHere: "The form with the strongest mucosal-healing evidence.", bestFor: "Gastric ulcer history, NSAID gut", internalSlug: "leaky-gut-without-the-hype" },
  { asin: "B0013OVW0E", title: "Saccharomyces boulardii capsules", brand: "Jarrow Formulas", family: "Supplement", category: "Gut barrier", whyHere: "A non-colonizing yeast that supports the gut lining and limits opportunistic species.", bestFor: "Post-antibiotic, traveler's diarrhea history" },
  { asin: "B01DOBJ84U", title: "Bone broth protein, unflavored", brand: "Ancient Nutrition", family: "Supplement", category: "Gut barrier", whyHere: "Concentrated collagen and amino acids for connective tissue and gut lining.", bestFor: "AIP and post-AIP rebuild" },
  { asin: "B000FGWDPE", title: "Perma-Clear gut barrier formula", brand: "Thorne", family: "Supplement", category: "Gut barrier", whyHere: "Combination of glutamine, larch arabinogalactan and probiotic for gut lining.", bestFor: "Post-AIP maintenance" },
  { asin: "B000FH11M4", title: "GI Revive powder", brand: "Designs for Health", family: "Supplement", category: "Gut barrier", whyHere: "Practitioner-grade gut rebuild formula with glutamine, DGL, slippery elm.", bestFor: "Aggressive gut repair phase" },
  { asin: "B004VCOOUU", title: "Ubiquinol CoQ10 100 mg", brand: "Jarrow Formulas", family: "Supplement", category: "Mitochondria", whyHere: "Reduced form, better absorbed than ubiquinone in older adults.", bestFor: "Fatigue, statin users", internalSlug: "mitochondria-and-autoimmune-fatigue" },
  { asin: "B0027DWNHQ", title: "Acetyl-L-carnitine 500 mg", brand: "Jarrow Formulas", family: "Supplement", category: "Mitochondria", whyHere: "Carrier of fatty acids into mitochondria; the acetyl form crosses the blood-brain barrier.", bestFor: "Brain fog, neuropathy, fatigue", warning: "Avoid in untreated hypothyroidism without a clinician." },
  { asin: "B00CB50KXO", title: "PQQ 20 mg", brand: "Doctor's Best", family: "Supplement", category: "Mitochondria", whyHere: "Promotes mitochondrial biogenesis in human trials.", bestFor: "Stubborn fatigue", internalSlug: "mitochondria-and-autoimmune-fatigue" },
  { asin: "B000BD0RT0", title: "Magnesium glycinate 400 mg", brand: "Doctor's Best", family: "Supplement", category: "Mitochondria", whyHere: "The most consistently tolerated form for sleep and ATP cofactor needs.", bestFor: "Sleep, muscle tension", internalSlug: "supplement-essentials-for-autoimmune" },
  { asin: "B00JYFN6DU", title: "Methylated B-complex (B-Complex Plus)", brand: "Pure Encapsulations", family: "Supplement", category: "Mitochondria", whyHere: "Active forms (methylfolate, methylcobalamin, P-5-P) for known MTHFR variants.", bestFor: "Suspected methylation issues" },
  { asin: "B004I53AT6", title: "D-ribose powder", brand: "NOW Foods", family: "Supplement", category: "Mitochondria", whyHere: "Pentose sugar used in ATP regeneration; helpful in chronic fatigue and fibromyalgia.", bestFor: "Post-exertional malaise" },
  { asin: "B000NRTWKO", title: "Alpha-lipoic acid 600 mg", brand: "Doctor's Best", family: "Supplement", category: "Mitochondria", whyHere: "Recycles glutathione, supports nerve health.", bestFor: "Diabetic-style neuropathy, oxidative load" },
  { asin: "B0DVWTMTPX", title: "Creatine monohydrate", brand: "Thorne", family: "Supplement", category: "Mitochondria", whyHere: "Phosphocreatine system support; small but real cognitive benefit in autoimmune fatigue.", bestFor: "Low-energy training, post-illness deconditioning" },
  { asin: "B0GGLLWLH8", title: "Nicotinamide riboside (NR) 300 mg", brand: "Double Wood", family: "Supplement", category: "Mitochondria", whyHere: "Raises NAD+ levels; emerging evidence in age-related fatigue.", bestFor: "Post-viral fatigue" },
  { asin: "B006L8DWSC", title: "Mitochondrial Energy Optimizer", brand: "Life Extension", family: "Supplement", category: "Mitochondria", whyHere: "All-in-one carnitine, R-lipoic, PQQ, benfotiamine combination.", bestFor: "Stacking simplification" },
  { asin: "B000H85L5Y", title: "Selenium L-selenomethionine 200 mcg", brand: "Pure Encapsulations", family: "Supplement", category: "Thyroid", whyHere: "Two trials show TPO antibody reduction in Hashimoto's at this dose.", bestFor: "Confirmed Hashimoto's", warning: "Ceiling 400 mcg/day; selenium toxicity is real.", internalSlug: "selenium-iodine-and-hashimotos" },
  { asin: "B000OSQP3E", title: "Kelp iodine 150 mcg", brand: "NOW Foods", family: "Supplement", category: "Thyroid", whyHere: "Whole-food iodine at conservative dose; helpful when intake is genuinely low.", bestFor: "Vegan diets, low-salt diets", warning: "Do not exceed 150 mcg/day in Hashimoto's without a clinician." },
  { asin: "B0G4XN31BL", title: "Ashwagandha KSM-66 600 mg", brand: "Sports Research", family: "Adaptogen", category: "Thyroid", whyHere: "Small trials show modest TSH and T3 improvement in subclinical hypothyroid.", bestFor: "Stress-driven thyroid dysregulation", warning: "Caution in hyperthyroid presentations." },
  { asin: "B0013OUPSE", title: "L-tyrosine 500 mg", brand: "NOW Foods", family: "Supplement", category: "Thyroid", whyHere: "Precursor amino acid for thyroid hormone synthesis.", bestFor: "Hypothyroid presentations after a blood-test conversation" },
  { asin: "B00O59SH3E", title: "Basic Prenatal (clean methylated)", brand: "Thorne", family: "Supplement", category: "Thyroid", whyHere: "Includes selenium and iodine in physiologic ratios; useful baseline for women with thyroid history.", bestFor: "Pre-conception, postpartum" },
  { asin: "B07NXW4GW7", title: "Vitamin D3 5000 IU + K2 MK-7", brand: "Sports Research", family: "Supplement", category: "Immune baseline", whyHere: "K2 directs calcium to bone away from arteries; 5000 IU is the most-studied autoimmune dose.", bestFor: "Confirmed low 25-OH-D, autoimmune diagnosis", warning: "Test before dosing; ceiling 10,000 IU/day except under clinician.", internalSlug: "supplement-essentials-for-autoimmune" },
  { asin: "B00LN3MN26", title: "Extra-virgin cod liver oil, unflavored", brand: "Rosita", family: "Supplement", category: "Immune baseline", whyHere: "Whole-food vitamin A and D in their natural ratio.", bestFor: "Old-school immune support, dry skin" },
  { asin: "B0739KKHWL", title: "Ultimate Omega EPA/DHA, triglyceride form", brand: "Nordic Naturals", family: "Supplement", category: "Immune baseline", whyHere: "TG-form is better absorbed than ethyl ester; resolution-of-inflammation literature.", bestFor: "Almost everyone with autoimmune disease" },
  { asin: "B0797FSF89", title: "Meriva-SF curcumin phytosome 500 mg", brand: "Thorne", family: "Supplement", category: "Immune baseline", whyHere: "Phytosome form is 30x more bioavailable than ordinary curcumin.", bestFor: "Joint inflammation, RA presentations", internalSlug: "rheumatoid-arthritis-real-talk" },
  { asin: "B0797DQTVZ", title: "Quercetin phytosome", brand: "Thorne", family: "Supplement", category: "Immune baseline", whyHere: "Phytosome quercetin is dramatically better absorbed; mast-cell stabilizer.", bestFor: "Itching, hives, IgE-flavored autoimmune presentations", internalSlug: "igg-food-sensitivity-tests-honestly" },
  { asin: "B00290G2HO", title: "Resveratrol Supreme", brand: "Designs for Health", family: "Supplement", category: "Immune baseline", whyHere: "Polyphenol with broad anti-inflammatory action; pterostilbene combo for stability.", bestFor: "Cardiometabolic-leaning autoimmune" },
  { asin: "B000R2X33M", title: "Milk thistle (silymarin) 175 mg", brand: "Nature's Way", family: "Herb", category: "Detox", whyHere: "Hepatoprotective in NAFLD and chemical-load contexts.", bestFor: "Sluggish liver presentations" },
  { asin: "B001DJ6J5W", title: "Bentonite clay (food grade)", brand: "Redmond", family: "Supplement", category: "Detox", whyHere: "Binds bile and certain mycotoxins in the gut.", bestFor: "Suspected mold exposure", warning: "Avoid within 2 hours of medications.", internalSlug: "mold-and-mycotoxin-illness" },
  { asin: "B0C5KK2KDS", title: "Activated charcoal capsules", brand: "Bulk Supplements", family: "Supplement", category: "Detox", whyHere: "Acute binder for occasional GI distress; not a daily tool.", bestFor: "Food poisoning, occasional bloat", warning: "Will bind medications too." },
  { asin: "B0013YYNDM", title: "Castor oil cold-pressed in glass", brand: "Heritage Store", family: "Topical", category: "Detox", whyHere: "Castor packs are an old-school lymph and gallbladder tool.", bestFor: "Right-upper-quadrant fullness, lymphatic stagnation" },
  { asin: "B00BBD508C", title: "Magnesium chloride flakes", brand: "Ancient Minerals", family: "Topical", category: "Detox", whyHere: "Transdermal magnesium for evening parasympathetic priming.", bestFor: "Sleep, sore muscles" },
  { asin: "B002MQMA2G", title: "Interfase Plus biofilm enzyme", brand: "Klaire Labs", family: "Supplement", category: "Detox", whyHere: "Practitioner-grade biofilm disrupter for SIBO and dysbiosis protocols.", bestFor: "Stubborn gut dysbiosis", warning: "Use only under clinician supervision." },
  { asin: "B00GZRJ97M", title: "ZenAdapt liver support", brand: "Designs for Health", family: "Supplement", category: "Detox", whyHere: "Combination of glutathione precursors and bitter herbs for liver phase I/II.", bestFor: "Chemical-load presentations" },
  { asin: "B07D32VNLP", title: "Reishi mushroom extract", brand: "Real Mushrooms", family: "TCM", category: "Adaptogen", whyHere: "TCM 'shen tonic'; modulates Th1/Th2 balance in cell-line studies.", bestFor: "Chronic stress, sleep, Th2-dominant presentations" },
  { asin: "B0793FB3LQ", title: "Cordyceps militaris extract", brand: "Real Mushrooms", family: "TCM", category: "Adaptogen", whyHere: "Energy and stamina support, modest evidence for VO2max.", bestFor: "Fatigue, athletic recovery" },
  { asin: "B01DKZZFCE", title: "Lion's mane extract", brand: "Real Mushrooms", family: "TCM", category: "Adaptogen", whyHere: "Nerve growth factor support; emerging cognitive evidence.", bestFor: "Brain fog, autoimmune-adjacent neuropathy" },
  { asin: "B07D3H6H6Y", title: "Turkey tail extract", brand: "Real Mushrooms", family: "TCM", category: "Adaptogen", whyHere: "PSK/PSP polysaccharides; balanced immune modulation.", bestFor: "Frequent infections, recovering immune systems" },
  { asin: "B01N1FV2RR", title: "Chaga extract", brand: "Real Mushrooms", family: "TCM", category: "Adaptogen", whyHere: "Antioxidant-dense polysaccharides; traditional Siberian tonic.", bestFor: "Oxidative-load presentations" },
  { asin: "B0036THNA2", title: "Rhodiola rosea standardized", brand: "Gaia Herbs", family: "Adaptogen", category: "Adaptogen", whyHere: "Best-studied adaptogen for stress-related fatigue.", bestFor: "HPA dysregulation, low motivation", warning: "Stimulating; take in the morning." },
  { asin: "B00AFBZZLS", title: "Triphala powder", brand: "Banyan Botanicals", family: "Herb", category: "Digestion", whyHere: "Three-fruit Ayurvedic digestive tonic; gentle and well-tolerated.", bestFor: "Sluggish digestion" },
  { asin: "B009LI7VRC", title: "Berberine 500 mg", brand: "Thorne", family: "Herb", category: "Microbiome", whyHere: "Antimicrobial action against opportunistic gut species; insulin-sensitizer.", bestFor: "Suspected SIBO, dysbiosis, insulin resistance", warning: "Avoid in pregnancy; can drop blood sugar.", internalSlug: "gi-map-and-stool-testing" },
  { asin: "B000ABCYGM", title: "Astragalus root", brand: "Nature's Answer", family: "TCM", category: "Adaptogen", whyHere: "TCM 'wei qi' tonic; supports Th1 immunity.", bestFor: "Frequent infections, post-viral fatigue" },
  { asin: "B0036THMJY", title: "Schisandra berry", brand: "Gaia Herbs", family: "TCM", category: "Adaptogen", whyHere: "Five-flavor berry; classical liver and adrenal tonic.", bestFor: "Stress with mild liver-function complaints" },
  { asin: "B003HDK0VG", title: "Maca root", brand: "Gaia Herbs", family: "Adaptogen", category: "Hormones", whyHere: "Andean adaptogen; gentle support for libido and vitality.", bestFor: "Perimenopause, libido" },
  { asin: "B003VT3YP0", title: "Vitex (chasteberry)", brand: "Gaia Herbs", family: "Herb", category: "Hormones", whyHere: "Pituitary-acting herb for luteal-phase support.", bestFor: "PMS, perimenopause cycle irregularity", internalSlug: "perimenopause-and-autoimmune-flares" },
  { asin: "B006KL4TYG", title: "DIM (diindolylmethane)", brand: "Smoky Mountain Naturals", family: "Supplement", category: "Hormones", whyHere: "Indole-3-carbinol metabolite; supports estrogen detoxification.", bestFor: "Estrogen-dominant presentations" },
  { asin: "B000FH11L0", title: "FemGuard+Balance", brand: "Designs for Health", family: "Supplement", category: "Hormones", whyHere: "Practitioner-grade combination of DIM, calcium-D-glucarate, broccoli seed for estrogen metabolism.", bestFor: "Estrogen-dominant cycles" },
  { asin: "B006RQ6TAG", title: "Saw palmetto 320 mg", brand: "Doctor's Best", family: "Herb", category: "Men's", whyHere: "Standardized extract for prostate health.", bestFor: "Older men with urinary symptoms", internalSlug: "men-autoimmune-and-the-stories-we-skip" },
  { asin: "B0062ENDCU", title: "Inositol 4 g powder", brand: "Designs for Health", family: "Supplement", category: "Blood sugar", whyHere: "Insulin-sensitizing in PCOS and metabolic-syndrome contexts.", bestFor: "Insulin resistance" },
  { asin: "B00172YQHI", title: "Chromium picolinate 200 mcg", brand: "Pure Encapsulations", family: "Supplement", category: "Blood sugar", whyHere: "Modest evidence for fasting glucose support.", bestFor: "Borderline metabolic markers" },
  { asin: "B07ZPFBQ1N", title: "Meta-Balance (women's hormonal)", brand: "Thorne", family: "Supplement", category: "Hormones", whyHere: "Combined hormone-rebalancing botanicals targeted at perimenopause.", bestFor: "Perimenopause symptoms" },
  { asin: "B086K54TZH", title: "Magnesium glycinate (evening dose)", brand: "Klean Athlete", family: "Supplement", category: "Nervous system", whyHere: "Glycine + magnesium = parasympathetic priming for sleep.", bestFor: "Sleep, anxiety", internalSlug: "vagus-nerve-and-the-anti-inflammatory-reflex" },
  { asin: "B00GQV9YX6", title: "L-theanine 200 mg (Suntheanine)", brand: "NOW Foods", family: "Supplement", category: "Nervous system", whyHere: "Increases alpha-wave EEG activity, gentle anxiolysis without sedation.", bestFor: "Daytime stress, anxious presentations" },
  { asin: "B000X9QZZ2", title: "Melatonin 300 mcg low-dose", brand: "Life Extension", family: "Supplement", category: "Nervous system", whyHere: "Low physiologic dose; high-dose melatonin is rarely better and often worse.", bestFor: "Jet lag, intermittent sleep", warning: "Avoid in autoimmune thyroid without a clinician.", internalSlug: "sleep-as-the-quietest-anti-inflammatory" },
  { asin: "B09DGTBBSF", title: "Apigenin 50 mg", brand: "Double Wood", family: "Supplement", category: "Nervous system", whyHere: "Chamomile-derived; mild GABAergic action.", bestFor: "Sleep onset" },
  { asin: "B0036THLL8", title: "Hawthorn berry capsules", brand: "Gaia Herbs", family: "Herb", category: "Nervous system", whyHere: "Cardiovascular tonic with mild parasympathetic effect.", bestFor: "Resting-heart-rate driven by stress" },
  { asin: "B079NDBYGP", title: "Lemon balm (Melissa) extract", brand: "Gaia Herbs", family: "Herb", category: "Nervous system", whyHere: "Gentle daytime calming herb; supports cognition.", bestFor: "Anxiety with mental fatigue" },
  { asin: "B00028OWPO", title: "Kava kava root", brand: "Nature's Way", family: "Herb", category: "Nervous system", whyHere: "Traditional South Pacific anxiolytic; works fast.", bestFor: "Acute anxiety", warning: "Use short-term only; avoid with liver disease." },
  { asin: "B00GDXHBS2", title: "5-HTP 100 mg", brand: "Thorne", family: "Supplement", category: "Nervous system", whyHere: "Serotonin precursor; mood and sleep support.", bestFor: "Low-mood, late-luteal PMS", warning: "Avoid with SSRI/SNRI without clinician." },
  { asin: "B000FGXLK0", title: "Adrenotone HPA support", brand: "Designs for Health", family: "Supplement", category: "Nervous system", whyHere: "Practitioner combination of rhodiola, ashwagandha, licorice for HPA support.", bestFor: "Wired-tired pattern" },
  { asin: "B0031TRUOG", title: "Cortisol Manager", brand: "Integrative Therapeutics", family: "Supplement", category: "Nervous system", whyHere: "Most prescribed natural sleep formula in functional medicine.", bestFor: "Cortisol-driven insomnia" },
  { asin: "B00K5NEORM", title: "Whole-food multivitamin (women's)", brand: "Garden of Life mykind Organics", family: "Supplement", category: "Foundations", whyHere: "Organic, plant-based multi for women; non-synthetic.", bestFor: "Real-food-first lifestyles" },
  { asin: "B00FOTMGTU", title: "Basic Nutrients 2/day multivitamin", brand: "Thorne", family: "Supplement", category: "Foundations", whyHere: "Methylated, no fillers, NSF-certified for sport.", bestFor: "Athletes, methylation-aware" },
  { asin: "B00CBYG1L0", title: "ONE multivitamin", brand: "Pure Encapsulations", family: "Supplement", category: "Foundations", whyHere: "Once-daily methylated multi.", bestFor: "Low-pill-burden preference" },
  { asin: "B000FGXLVE", title: "Twice Daily Multi", brand: "Designs for Health", family: "Supplement", category: "Foundations", whyHere: "Practitioner-grade methylated multi with chelated minerals.", bestFor: "Functional medicine baseline" },
  { asin: "B00HST919C", title: "Basic B Complex", brand: "Thorne", family: "Supplement", category: "Foundations", whyHere: "Standalone methylated B complex when not using a multi.", bestFor: "MTHFR-aware" },
  { asin: "B00JZ246S6", title: "Ther-Biotic Complete probiotic", brand: "Klaire Labs", family: "Supplement", category: "Microbiome", whyHere: "Practitioner-grade 12-strain blend.", bestFor: "Broad gut support" },
  { asin: "B0072POOHG", title: "FloraMend Prime probiotic", brand: "Thorne", family: "Supplement", category: "Microbiome", whyHere: "Targeted for digestion and metabolic support.", bestFor: "GI regularity" },
  { asin: "B00Y8MP4G6", title: "Dr. Formulated probiotic (women)", brand: "Garden of Life", family: "Supplement", category: "Microbiome", whyHere: "Strain-specific women's-formula with cranberry support.", bestFor: "Recurrent UTIs" },
  { asin: "B000FL9EAG", title: "Primadophilus reuteri", brand: "Nature's Way", family: "Supplement", category: "Microbiome", whyHere: "Single-strain L. reuteri for histamine-friendly support.", bestFor: "Histamine-intolerant gut" },
  { asin: "B003PQNNTG", title: "L. rhamnosus GG single strain", brand: "Klaire Labs", family: "Supplement", category: "Microbiome", whyHere: "Most-studied probiotic strain in atopic and gut conditions.", bestFor: "Eczema, IBS" },
  { asin: "B07F21JLC8", title: "ProbioMed 50 high-dose probiotic", brand: "Designs for Health", family: "Supplement", category: "Microbiome", whyHere: "50 billion CFU practitioner-grade probiotic.", bestFor: "Post-antibiotic restoration" },
  { asin: "B000MGSI1K", title: "Inulin prebiotic powder", brand: "NOW Foods", family: "Supplement", category: "Microbiome", whyHere: "Soluble fiber that feeds beneficial bacteria.", bestFor: "Constipation-leaning stools", warning: "Avoid with active SIBO." },
  { asin: "B000I4DGRW", title: "Oregano oil softgels", brand: "Nature's Answer", family: "Herb", category: "Antimicrobial", whyHere: "Carvacrol-rich; broad antimicrobial spectrum.", bestFor: "SIBO protocols", warning: "Use 4-6 weeks max under clinician." },
  { asin: "B0030HQ0M2", title: "ADP emulsified oregano", brand: "Biotics Research", family: "Herb", category: "Antimicrobial", whyHere: "Time-released oregano for protocols.", bestFor: "SIBO/dysbiosis protocols" },
  { asin: "B01MQGGFFA", title: "GI Microb-X antimicrobial", brand: "Designs for Health", family: "Herb", category: "Antimicrobial", whyHere: "Practitioner antimicrobial blend (berberine, oregano, caprylic acid).", bestFor: "Functional medicine SIBO protocols" },
  { asin: "B000S85GQC", title: "Garlic extract glycerite", brand: "Herb Pharm", family: "Herb", category: "Antimicrobial", whyHere: "Broad-spectrum botanical antimicrobial; cardiovascular bonus.", bestFor: "Mild gut overgrowths" },
  { asin: "B0014AU5MI", title: "Goldenseal liquid extract", brand: "Herb Pharm", family: "Herb", category: "Antimicrobial", whyHere: "Berberine-rich North American botanical.", bestFor: "Acute mucosal infections", warning: "Short-term use only; avoid in pregnancy." },
  { asin: "B007LU5P0M", title: "Arnica montana 30C pellets", brand: "Boiron", family: "Topical", category: "Pain & inflammation", whyHere: "Homeopathic standby for soreness, bruising.", bestFor: "Post-exercise soreness, mild trauma" },
  { asin: "B001ECQ69C", title: "Tiger Balm extra strength", brand: "Tiger Balm", family: "Topical", category: "Pain & inflammation", whyHere: "Camphor-menthol classic for acute joint and muscle aches.", bestFor: "Stiff necks, sore shoulders" },
  { asin: "B0GMRG5CRK", title: "Biofreeze cold-therapy gel", brand: "Biofreeze", family: "Topical", category: "Pain & inflammation", whyHere: "Menthol-based topical analgesic; gym standard.", bestFor: "Acute musculoskeletal pain" },
  { asin: "B08H4M2SD6", title: "Voltaren arthritis pain gel (diclofenac)", brand: "Voltaren", family: "Topical", category: "Pain & inflammation", whyHere: "Topical NSAID with strong evidence for hand and knee OA.", bestFor: "Localized OA pain", warning: "Read NSAID precautions on the label." },
  { asin: "B000OS131S", title: "Arnica massage oil", brand: "Weleda", family: "Topical", category: "Pain & inflammation", whyHere: "European herbal classic for muscle recovery.", bestFor: "Post-exercise" },
  { asin: "B005GMFWXW", title: "Peppermint essential oil (food grade)", brand: "NOW Foods", family: "Topical", category: "Pain & inflammation", whyHere: "Topical headache aid; in enteric capsules helps IBS.", bestFor: "Tension headaches" },
  { asin: "B0012QMAHM", title: "Digest Gold broad-spectrum enzymes", brand: "Enzymedica", family: "Supplement", category: "Digestion", whyHere: "High-activity enzyme blend for protein, fat, carb, fiber.", bestFor: "Bloating, low-stomach-acid pattern" },
  { asin: "B01D8V0962", title: "Curcumin Phytosome 500 mg", brand: "Thorne", family: "Supplement", category: "Joints", whyHere: "Phytosome curcumin for joint inflammation.", bestFor: "Joint inflammation" },
  { asin: "B000I4DFAK", title: "Glucosamine + chondroitin + MSM", brand: "Doctor's Best", family: "Supplement", category: "Joints", whyHere: "Classic joint structural support; modest but real evidence in OA.", bestFor: "Osteoarthritis" },
  { asin: "B0BKG2HKCM", title: "Boswellia serrata extract", brand: "Nature's Way", family: "Herb", category: "Joints", whyHere: "5-LOX inhibitor; useful in inflammatory joint conditions.", bestFor: "RA-style joint pain", internalSlug: "rheumatoid-arthritis-real-talk" },
  { asin: "B0013OUPXE", title: "MSM 1000 mg", brand: "NOW Foods", family: "Supplement", category: "Joints", whyHere: "Sulfur-donor; supports collagen/joint integrity.", bestFor: "Connective tissue maintenance" },
  { asin: "B000VYQJ8W", title: "Bio-Gest digestive enzyme + bile", brand: "Thorne", family: "Supplement", category: "Digestion", whyHere: "Combined betaine HCl, ox bile, pancreatin for hard-to-digest meals.", bestFor: "Post-AIP reintroductions" },
  { asin: "B0006UII08", title: "Echinacea purpurea", brand: "Nature's Way", family: "Herb", category: "Antiviral", whyHere: "Acute respiratory immune support.", bestFor: "Onset of cold symptoms", warning: "Avoid in confirmed Th1-dominant autoimmune." },
  { asin: "B00142A5EE", title: "Elderberry extract", brand: "Herb Pharm", family: "Herb", category: "Antiviral", whyHere: "Anthocyanin-rich antiviral support.", bestFor: "Cold/flu prevention" },
  { asin: "B00CFCRH34", title: "Samento (cat's claw)", brand: "Nutramedix", family: "Herb", category: "Antiviral", whyHere: "TOA-free cat's claw used in chronic Lyme protocols.", bestFor: "Chronic stealth-infection presentations" },
  { asin: "B074FXRDLG", title: "Takesumi Supreme binder", brand: "Researched Nutritionals", family: "Supplement", category: "Detox", whyHere: "Bamboo charcoal binder for mold and biotoxins.", bestFor: "CIRS protocols" },
  { asin: "B00N55ASK4", title: "Flax oil omega-3 (vegan)", brand: "Barlean's", family: "Supplement", category: "Skin", whyHere: "Vegan ALA omega-3 for skin barrier.", bestFor: "Plant-based diets" },
  { asin: "B0DG493HH1", title: "Biotin (hair, skin, nails)", brand: "Garden of Life", family: "Supplement", category: "Skin", whyHere: "Whole-food biotin for connective tissue + appendage health.", bestFor: "Hair thinning during autoimmune flare" },
  { asin: "B09RQBHRCT", title: "Collagen peptides, unflavored", brand: "Vital Proteins", family: "Supplement", category: "Skin", whyHere: "Hydrolyzed bovine collagen; skin and connective tissue support.", bestFor: "Skin elasticity, joint hair nails" },
  { asin: "B0078W0QOI", title: "Oscillococcinum flu remedy", brand: "Boiron", family: "Topical", category: "Acute care", whyHere: "Homeopathic acute-flu standby; gentle, well-tolerated.", bestFor: "Onset of flu-like symptoms" },
  { asin: "B000FGWBK6", title: "Magnesium Buffered Chelate", brand: "Designs for Health", family: "Supplement", category: "Mitochondria", whyHere: "Practitioner-grade buffered glycinate; gentler on gut.", bestFor: "Sensitive digestion" },
  { asin: "B0797HBLL3", title: "Magnesium Bisglycinate powder", brand: "Thorne", family: "Supplement", category: "Mitochondria", whyHere: "Powder form for higher dosing without 5+ capsules.", bestFor: "Athletes, large frames" },
  { asin: "B077V31X84", title: "Phosphatidylserine 100 mg", brand: "Doctor's Best", family: "Supplement", category: "Nervous system", whyHere: "Cortisol-modulating phospholipid; useful for evening dosing.", bestFor: "Cortisol-dysregulation pattern" },
  { asin: "B003BHSXPS", title: "Phosphatidylcholine 1200 mg", brand: "NOW Foods", family: "Supplement", category: "Detox", whyHere: "Cell-membrane support; lymphatic and detox protocols.", bestFor: "Mold/biotoxin recovery" },
  { asin: "B073DPB2HK", title: "Liposomal Glutathione", brand: "Designs for Health", family: "Supplement", category: "Detox", whyHere: "Bypasses gut breakdown for systemic glutathione delivery.", bestFor: "Oxidative-stress-heavy protocols" },
  { asin: "B003O1R73U", title: "Sublingual B12 methylcobalamin 5000 mcg", brand: "NOW Foods", family: "Supplement", category: "Foundations", whyHere: "Sublingual bypasses absorption issues common in autoimmune gastritis.", bestFor: "Pernicious anemia, vegan diets" },
  { asin: "B000KJPPTC", title: "Pyridoxal-5-phosphate (P-5-P)", brand: "Thorne", family: "Supplement", category: "Foundations", whyHere: "Active B6; supports neurotransmitter and hormone balance.", bestFor: "PMS, neurotransmitter support" },
  { asin: "B00HA044NM", title: "Copper bisglycinate 2 mg", brand: "Thorne", family: "Supplement", category: "Foundations", whyHere: "Pair to long-term zinc dosing to keep ratio sane.", bestFor: "Long-term zinc users" },
  { asin: "B0016QX5RC", title: "Biotin 8 mg", brand: "Designs for Health", family: "Supplement", category: "Foundations", whyHere: "High-dose biotin for hair/nail support.", bestFor: "Telogen effluvium during flare", warning: "Pause 48h before thyroid blood tests." },
  { asin: "B0797GZDZL", title: "Iron bisglycinate 25 mg", brand: "Thorne", family: "Supplement", category: "Foundations", whyHere: "Gentle iron for low-ferritin states; less constipating.", bestFor: "Confirmed iron deficiency", warning: "Test before dosing." },
  { asin: "B0011023NU", title: "Iodine + tyrosine combination", brand: "Designs for Health", family: "Supplement", category: "Thyroid", whyHere: "Conservative iodine + tyrosine pairing.", bestFor: "Thyroid maintenance after labs" },
  { asin: "B001RYKA3U", title: "Alpha-GPC 300 mg", brand: "Thorne", family: "Supplement", category: "Nervous system", whyHere: "Choline donor for cognitive support.", bestFor: "Brain fog, memory" },
  { asin: "B09SGKPG52", title: "Sulbutiamine 200 mg", brand: "Double Wood", family: "Supplement", category: "Nervous system", whyHere: "Lipid-soluble B1 for fatigue and cognition.", bestFor: "Subacute fatigue", warning: "Use cyclically; not daily long-term." },
  { asin: "B0CLDVR7X8", title: "L-Tyrosine 500 mg", brand: "Double Wood", family: "Supplement", category: "Nervous system", whyHere: "Catecholamine precursor; supports stress resilience.", bestFor: "Stress with low motivation" },
  { asin: "B015AEXKU2", title: "Adenosyl-hydroxy B12", brand: "Thorne", family: "Supplement", category: "Foundations", whyHere: "Alternative methyl form of B12 for sensitive responders.", bestFor: "Methyl-trapping pattern" },
  { asin: "B0B8PH3T94", title: "Organic moringa powder", brand: "NOW Foods", family: "Supplement", category: "Foundations", whyHere: "Whole-food micronutrient density; iron, calcium, polyphenols.", bestFor: "Real-food micronutrient gap" },
  { asin: "B0013OVZJW", title: "Glycine powder", brand: "Lake Avenue Nutrition", family: "Supplement", category: "Foundations", whyHere: "Inhibitory amino acid; sleep and collagen support.", bestFor: "Pre-bed sleep ritual" },
  { asin: "B01CUYHCX6", title: "Taurine 1000 mg", brand: "Thorne", family: "Supplement", category: "Foundations", whyHere: "Bile-conjugating, GABA-modulating, cardioprotective amino acid.", bestFor: "Stress-driven blood pressure swings" },
  { asin: "B0012MZZLE", title: "Calcium D-glucarate 500 mg", brand: "Thorne", family: "Supplement", category: "Hormones", whyHere: "Supports beta-glucuronidase pathway for estrogen elimination.", bestFor: "Estrogen-dominant patterns" },
  { asin: "B00ASZ2QNQ", title: "Raw Probiotics 50 billion", brand: "Garden of Life", family: "Supplement", category: "Microbiome", whyHere: "Soil-based + lacto/bifido blend.", bestFor: "Whole-microbiome support" },
  { asin: "B000WSMPQW", title: "Phosphatidyl Serine 100 mg", brand: "NOW Foods", family: "Supplement", category: "Nervous system", whyHere: "Cortisol-blunting evening support.", bestFor: "Wired-tired pattern" },
  { asin: "B00B8YTP12", title: "Zinc picolinate 30 mg", brand: "Thorne", family: "Supplement", category: "Foundations", whyHere: "Best-absorbed common zinc form; immune and connective tissue.", bestFor: "Recurrent infections" },
  { asin: "B003YEU43C", title: "Hist-All C", brand: "Designs for Health", family: "Supplement", category: "Immune baseline", whyHere: "Quercetin + bromelain + nettle + C for histamine days.", bestFor: "Allergy-flavored autoimmune" },
  { asin: "B00CP7S2L0", title: "Quercetin + bromelain", brand: "Natural Factors", family: "Supplement", category: "Immune baseline", whyHere: "Mast-cell-stabilizing pair.", bestFor: "Histamine-prone individuals" },
  { asin: "B001WU1XUS", title: "ArthroSoothe joint blend", brand: "Designs for Health", family: "Supplement", category: "Joints", whyHere: "Boswellia + curcumin + glucosamine + MSM combination.", bestFor: "Refractory OA/RA" },
];

export const FAMILIES: Family[] = ["Supplement", "Herb", "TCM", "Adaptogen", "Topical"];
export const CATEGORIES = Array.from(new Set(APOTHECARY.map((i) => i.category))).sort();
